# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0069_auto_20180120_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSource',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('key', models.AutoField(primary_key=True, serialize=False, verbose_name='identifier')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='judge.ProblemSource', verbose_name='parent item')),
            ],
            options={
                'verbose_name': 'problem source item',
                'verbose_name_plural': 'problem sources',
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.CharField(default=b'2018AZ', help_text='Organization name shows in URL', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(b'^[A-Za-z0-9]+$', b'Identifier must contain letters and numbers only')], verbose_name='identifier'),
        ),
    ]
